### ISSUE TITLE
Bibletime 2.11 - can't install any works

### ISSUE THREAD

**Issue by ngoonee** [bibletime/bibletime#124]
In the Bookshelf Manager, after doing a 'get list', whichever of the sources I select, when I click 'next' I don't see any languages listed. Am I doing something wrong?

Running on Linux.

**Comment by gholmlund** [comment]
On the "Choose Remote Libraries" path you should see 8 libraries. Then you are choosing 1 or more libraries and selecting "next"? And then you don't see any languages?

**Comment by ngoonee** [comment]
Yes exactly. I've chosen only Crosswire as well as all of them, and no languages are shown.

Is there any debug mode I could run to see what it's trying to do?

**Comment by gholmlund** [comment]
There is not a debug mode related to the bookshelf. What platform is this on?
My best guess is there is a bad file or wrong permissions in your sword directory. This is $HOME/.sword in linux. You could try renaming or removing this directory and trying again.

**Comment by ngoonee** [comment]
I've definitely removed and recreated the directory multiple times while
trying to debug this. Permissions are fairly standard for my HOME, as far
as I can see.

**Comment by gholmlund** [comment]
Another suggestion. Using a text editor, delete a line in the $HOME/.bibletime/bibletimerc file. Remove the line that begins with "BookshelfWizard\lastUpdate". This will force the update of your remote libraries.

**Comment by ngoonee** [comment]
That worked, thanks. What did I do wrong prior to this?

**Comment by gholmlund** [comment]
That entry causes BibleTime to automatically update remote libraries no more often than one week. Deleting $HOME/.sword removes the remote library information and that entry prevents it from auto updating. This is really a deficiency in BibleTime. We either need a manual refresh button or a better algorithm to know when to auto update the remote libraries.

**Comment by jaakristioja** [comment]
If a manual refresh button requires no new translatable strings, it might be possible to include a fix this in 2.11.2.

**Comment by jaakristioja** [comment]
On the other hand, a non-user-visible solution might be better (such as always refreshing the library every time the wizard is run, or in case no works are found).

**Comment by gholmlund** [comment]
This change covers the case when a user has installed works, then removed the $HOME/.sword dir and wants to install more works.

**Comment by ngoonee** [comment]
Just tried it and it does what it says on the tin. Thanks

**Comment by NB-Productions** [comment]
![Image](https://github.com/user-attachments/assets/3066a902-9538-4ea3-b348-4aea23ced38f)

The bookshelf manager is not functional. I am using Debian 12 and it's a fairly recent install due to a crash that left me unable to recover from as I lost my root. I have a separate Home partition but this shouldn't be a problem as I've had no other problems with any other programs I have installed and everything seems to work as it should.

I've tried uninstalling and purging, before reinstalling again; still no luck. I've tried following the advice in the above post, but there is no entry 'BookshelfWizard\lastUpdate' to delete.

**Comment by greg-hellings** [comment]
@NB-Productions If you still have Bible time 2.11 installed, please work with Debian maintainers to update, as that version is somewhere around 7 years out of date.

**Comment by greg-hellings** [comment]
Because this bug report was specific to version 2.11.

3.0 is also no longer in support. Can you try with 3.1.1 and see if it still suffers this behavior?

**Comment by NB-Productions** [comment]
It seems I am unable to make the file because of the following error:

bibletime-3.1.1/src/backend/bookshelfmodel/btbookshelftreemodel.cpp: In function ‘QDataStream& operator>>(QDataStream&, BtBookshelfTreeModel::Grouping&)’:
/home/neil/Downloads/Program Files/bibletime-3.1.1/src/backend/bookshelfmodel/btbookshelftreemodel.cpp:647:36: error: static assertion failed: Platform not supported
  647 |         static_assert(sizeof(Size) == 8, "Platform not supported");
      |                       ~~~~~~~~~~~~~^~~~
/home/neil/Downloads/Program Files/bibletime-3.1.1/src/backend/bookshelfmodel/btbookshelftreemodel.cpp:647:36: note: the comparison reduces to ‘(4 == 8)’
make[2]: *** [CMakeFiles/bibletime_backend.dir/build.make:118: CMakeFiles/bibletime_backend.dir/src/backend/bookshelfmodel/btbookshelftreemodel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:276: CMakeFiles/bibletime_backend.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by greg-hellings** [comment]
Please open a separate bug about that, as this bug has been closed for years because it is resolved. Once you get your build issue resolved, you can open a new issue for the install if it persists in the new version.
