### ISSUE TITLE
BibleTime 2.11.1 won't start (core dump) on Fedora 27

### ISSUE THREAD

**Issue by chiastic-security** [bibletime/bibletime#125]
When I try to start BibleTime on Fedora 27, I get:

    [james@marlon jeremiah] $ bibletime 
    (BibleTime 2.11.1) WARNING: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
    (BibleTime 2.11.1) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior 
    QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  
    QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
    Please report this bug at https://github.com/bibletime/bibletime/issues
    [1:1:0100/000000.720408:ERROR:broker_posix.cc(41)] Invalid node channel message
    Aborted (core dumped)
    [james@marlon jeremiah] $

It was working on Fedora 26 last time I tried it (within the last few months).

**Comment by greg-hellings** [comment]
The Fedora package needs to be rebuilt. When the Qt package was updated
from 5.9.1 to 5.9.2 it resulted in ABI changes that necessitate a rebuild.
I'm AFK for the US holiday this week. I'll try to get online and update it,
hopefully before the weekend if I can find WiFi for my laptop.

On Nov 21, 2017 3:35 PM, "James Heather" <notifications@github.com> wrote:

When I try to start BibleTime on Fedora 27, I get:

[james@marlon jeremiah] $ bibletime
(BibleTime 2.11.1) WARNING: WebEngineContext used before
QtWebEngine::initialize() or OpenGL context creation failed.
(BibleTime 2.11.1) FATAL: Failed to create OpenGL context for format
QSurfaceFormat(version 2.0, options
QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24,
redBufferSize -1, greenBufferSize -1, blueBufferSize -1,
alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior
QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile
QSurfaceFormat::OpenGLContextProfile(NoProfile))
Please report this bug at https://github.com/bibletime/bibletime/issues
[1:1:0100/000000.720408:ERROR:broker_posix.cc(41)
<https://github.com/bibletime/bibletime/issues%5B1:1:0100/000000.720408:ERROR:broker_posix.cc(41)>]
Invalid node channel message
Aborted (core dumped)
[james@marlon jeremiah] $

It was working on Fedora 26 last time I tried it (within the last few
months).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bibletime/bibletime/issues/125>, or mute the thread

**Comment by chiastic-security** [comment]
@greg-hellings just a reminder that Bibletime is still broken for Fedora 27...

**Comment by greg-hellings** [comment]
I'm running fully updated F27 and it "works for me". This issue is going to have to go back to one of the devs. Perhaps you can try running Bibletime to pull a backtrace from gdb to help them out.

**Comment by gholmlund** [comment]
I have tried BibleTime on Fedora 27 and it is working correctly for me. I have dtried with both Wayland and Xorg logins.
I have tried googling for these error messages. I have seen several reports like this on various OS platforms. I could not find answers to the problem, but they seemed to suggest issues either in OpenGL or the video driver. Please tell us about your video hardware and drivers.

**Comment by gholmlund** [comment]
Since we cannot reproduce this I am closing it. If more information is available to help reproduce this, re-open this and add here.
