### ISSUE TITLE
German Umlautletters not correctly displayed

### ISSUE THREAD

**Issue by bodiro** [bibletime/bibletime#143]
In the Textmodules GerLeoRP05 and GerLeoNA28 footnotes are not correctly displayed when they contain umlautletters. Example: "hort" instead of "hört" or "Bruder" instead of "Brüder".

**Comment by gholmlund** [comment]
Can you give a verse reference where this happens. Thanks.

**Comment by bodiro** [comment]
Matthew 5,9 where "Kinder" is explained literally as "Söhne" - displayed is "Sohne".

1 Corinthians 14,2 where "versteht" is given another meaning as "hört" - displayed is "hort".

1 Corithians 14,6 where "Geschwister" is explained literally as "Brüder" - displayed is "Bruder".

**Comment by gholmlund** [comment]
These reverences are working correctly for me. Pehaps it is related to the font setting for the German language. I am using "sans serif". Please try this font.

**Comment by bodiro** [comment]
Hm... No effect here when changing font to another. Even reinstalling the program does not help.

**Comment by jaakristioja** [comment]
Seems to work for me as well. To verify whether this is a font problem, you can try copy-pasting the footnote from the Mag to some other application. Holding the <kbd>Ctrl</kbd> key pressed while you move the mouse cursor to the Mag might be of help before copy-pasting.

**Comment by bodiro** [comment]
Did it. Umlautletters not displayed. Font problem?

**Comment by jaakristioja** [comment]
If the application you pasted the footnote to has support for formatted text, you might need to change the font of the pasted text to verify. But if you pasted it to a terminal or an text editor which does not preserve the formatting when pasting text, the result should be seen immediately. You could also just copy-paste the footnote to a GitHub comment here which does not preserve formatting.

**Comment by bodiro** [comment]
hort Bruder
Copied from footnotes.

**Comment by bodiro** [comment]
I am using bibletime 2.10.1 and sword 1.7.3 on KDE neon (Plasma 5.13.4 KDE Frameworks 5.49.0 Qt 5.11.1 Ubuntu 16.04).

**Comment by jaakristioja** [comment]
I can confirm this issue with BibleTime on Kubuntu 16.04:

* **BibleTime 2.10.1 from packages + Sword 1.7.3 from packages - issue reproduces**.
* BibleTime 2.10.1 from source + Sword 1.7.3 from packages - cannot reproduce issue.
* BibleTime 2.10.1 from source + Sword 1.7.3 from source - cannot reproduce issue.
* BibleTime 2.10.1 from packages + Sword 1.7.3 from source - cannot reproduce issue.
* **BibleTime 2.11.0 from source + Sword 1.7.3 from packages - issue reproduces**.
* BibleTime 2.11.0 from source + Sword 1.7.3 from source - cannot reproduce issue.
* **BibleTime 2.11.1 from source + Sword 1.7.3 from packages - issue reproduces**.
* BibleTime 2.11.1 from source + Sword 1.7.3 from Source - cannot reproduce issue.

This seems to be some strange packaging issue with in Ubuntu. After building and installing the libsword11v5, bibletime and bibletime-data Ubuntu packages from source the issue seems to be gone. I suggest to instead contact the bibletime/libsword11v5 packagers for Ubuntu and ask them to rebuild the binary packages to see if that fixes the issue. I think there is nothing we can do from our side. Additionally, we no longer actually support the 2.10 release series of BibleTime.

Leaving this issue closed.

PS: The bibletime-2.10.1-3 DEB package fails to build on Ubuntu without manually patching the source it with 56b5fa646c1439a047b925761fea8af78b848811.

**Comment by bodiro** [comment]
Anyhow, thanks for caring!
