### ISSUE TITLE
[Bug] Creating Scope with Deuterocanonical Books

### ISSUE THREAD

**Issue by PapistPenguin** [bibletime/bibletime#186]
Ubuntu 19.04 x64
BibleTime 2.11.2

Problem: I am unable to create a scope including the deuterocanonical books.

Steps
1. Open Bible (such as DRC)
2. In that pane, click the button to "search the works of this window"
3. Next to "Scope," click the "Setup..." button.
4. Try to enter a range for a deuterocanonical books (such as Tobias 1:1-2:1).
5. The "parsed search range" will remain empty. If protocanonical books are included in the "Edit current range:", they may be included in the parsed search range, but the range will exclude, it seems, the deuterocanonical books.

Please work on fixing this. BibleTime would be a great tool with this feature fully-functional.

**Comment by gholmlund** [comment]
I can confirm the above description. I will look into this.

**Comment by gholmlund** [comment]
There were several places that checked the validity of the entered verse range. These checks were using VerseKey::parseVerseListWithModules to do the validation. Because they used a generic Versekey (one without a module attached), they were only validating using the standard versification system. I had to change these to validate with each of the Bible works listed in this dialog. This allowed books like Tobit to work correctly.

@PapistPenguin 
If you want to verify this works, can you compile the master branch? I could also provide a linux snap file you could install with. Are you running linux?

**Comment by PapistPenguin** [comment]
Yes, I am running Ubuntu 19.04 x64. I would appreciate a snap file.

**Comment by gholmlund** [comment]
The snap is available here:
http://sourcearchives.com/downloads/bibletime_master-HEAD_amd64.snap

Install it like this:
sudo snap install --dangerous bibletime_master-HEAD_amd64.snap

Notes about the snap:
120 MBytes
Ignore the BibleTime version number.
The first time the snap starts may take 1 or 2 minutes. It is fast after that.
The snap runs in its own file space so it will not find your $HOME/.bibletime or $HOME/.sword

The snap is of our latest code which is not released yet. It has a new feature. You can scroll continuously past chapter and book boundaries. Please give me your feedback about this.

**Comment by PapistPenguin** [comment]
Thank you. It works now. It would be nice to be able to use the traditional naming of some of the books (such as Tobias, Paralipomenon, Machabees, etc.). However, that's more a feature request than a bug. Regarding the continuous scrolling, it is good. However, the text looks smaller than usual, which I do not like. I am not sure those two things are related, though. However, functionality is great.

**Comment by gholmlund** [comment]
Regarding the text size, you probably just need to set the font size in the settings dialog. Your previous settings don't load because the snap is using its own file space.
