### ISSUE TITLE
Problems with hebrew modules OSHB and OSMHB

### ISSUE THREAD

**Issue by kamilnovo** [bibletime/bibletime#194]
Dear developers,

I'm running BibleTime 2.11.2 on Windows 10 Home, Czech version.
BibleTime is my favorite bible app but I have the follwing problems with the Hebrew modules:
_OSHB and dictionary_
OSBH doesn't work with BDB Glosses (Strong's) works only with Strong's Real Hebrew Bible Dictionary. With BDB it only shows the Strong number but not the contents of the disctionary entry. Please see screenshot.
![oshb](https://user-images.githubusercontent.com/25617599/66260942-a982b580-e7c5-11e9-83bd-a77ee16aa878.png)

_OSMHB and Morphology_
OSMHB does not show Morpohology with either of the two dictionaries. But shows BDB, unlike OSHB which is great.  Screenshot below:
![osmhb](https://user-images.githubusercontent.com/25617599/66261021-c8ce1280-e7c6-11e9-81cf-b64bc43d66a5.png)

It would be enough for me if at least one of these modules would show both BDB dictionary and Morphology. 

Thank you in advance for looking into this.
Kamil

**Comment by gholmlund** [comment]
It seems to be a inconsistency of the reference. OSHB, StrongsRealHebrew,  and StrongsHebrew using a reference like H03405, but BDB uses H3405 (one less number).

**Comment by gholmlund** [comment]
Fix for Strongs lookup when number of digits in lookup reference are greater than the module where the references are found. Also, fix for the lookup reference in OSHB having a lowercase name, but the actual module has a uppercase name.
You will want to use OSHB because both the Strongs and morph work as you want. The OSMHB does not contain morph references. See the About context menu for more information about this.

Fixed in stable-2.11 and master branches.
