### ISSUE TITLE
Crossreference not working unless Settings/Configure has been done

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#204]
The Cross-reference in some dictionary and daily devotional modules are not working.

**Comment by gholmlund** [comment]
I found it works fine if you have the standard Bible set in your configuration.

**Comment by LAfricain** [comment]
What do you mean by standard BIble? Is it working with the frecallit?

**Comment by gholmlund** [comment]
I used FreCaLit2019 daily module with the KJV Bible. You must set KJV in the "Settings / Configure BibleTime / Desk / Standard works / Bible"

**Comment by LAfricain** [comment]
Just change the bible for an other and it worked. Thanks.

**Comment by jaakristioja** [comment]
What were the symptoms of "not working"? Perhaps we could improve the UI to display an informational or error dialog to the user, stating that the standard Bible is not set?

**Comment by LAfricain** [comment]
> What were the symptoms of "not working"?

The link of the cross-reference didn't show the cross-reference.

**Comment by gholmlund** [comment]
This problem begins in OsisToHtml::renderReference where the "standardBible" is looked up using the config system. When the standard Bible is not found, the cross reference is rendered as plain text instead of a html href. 
If a Bible is installed and the "Configure BibleTime" dialog is simply opened and OKed, the problem goes away. It would be a simple change to use the first available Bible if the standard Bible has not been set in the config dialog. Then you would only see this problem if no Bible was installed.

**Comment by gholmlund** [comment]
If no standard Bible has been configured, use the first available Bible for MAG crossrefs.
