### ISSUE TITLE
3..0_beta1 fails to build

### ISSUE THREAD

**Issue by timsoftgit** [bibletime/bibletime#210]
although requirements just specify qt 5.9 and std c+11 cmake versions earlier than 3.10 fail to work.

As cmake 3.5 is common on a number of distro;s this is a problem. Running the following commands fixes the CMakeLists.txt file so that it compiles on those earlier versions of cmake (and the resulting package/binary appears to work just fine as far as I can tell

sed -i "s/VERSION 3.10/VERSION 3.5/g" CMakeLists.txt
sed -i "s/^CHECK_IPO_SUPPORTED(RESULT HAVE_IPO)/SET(HAVE_IPO FALSE)/g" CMakeLists.txt
sed -i "s/^INCLUDE(CheckIPO/#INCLUDE(CheckIPO/g" CMakeLists.txt
sed -i "/TARGET_COMPILE_FEATURES/s/.*/SET(CMAKE_CXX_STANDARD 11)/" CMakeLists.txt

**Comment by jaakristioja** [comment]
This is because our build system currently requires CMake 3.10 or later. The changes you made to the CMakeLists.txt might work for you, but it might not work in the long term. There might be other features in the build system which depend on CMake >= 3.10, which you might have missed.

We have chosen not to support old versions of CMake, because CMake is very portable, building new versions of CMake is very simple, CMake is not a run-time dependency, and newer versions of CMake allow us to improve our build system the most. For BibleTime we chose to support the latest stable versions of CMake on the latest versions of Debian stable and Ubuntu LTS ([3.13.4](https://packages.debian.org/buster/cmake) and [3.10.2](https://packages.ubuntu.com/bionic/cmake) respectively).

We have no plans to backport our build system, but we might however consider mechanisms which will download, verify, build and use a newer version of CMake automatically during the build process. Using newer versions of CMake also eases development for our volunteer developers who don't have to much free time to keep the build system backwards compatible. We might also at one point require versions of CMake not yet packaged by any distribution, because it is a build-time dependency, not run-time dependency.

For clarity I have now added the information about requiring CMake >= 3.10 to the [release](https://github.com/bibletime/bibletime/releases/tag/v3.0_beta1).

If you really need to build on a system with CMake versions earlier than 3.10 installed, and no option to upgrade the system CMake, my best suggestion is this:
1. install (optionally compile from source and install) a new version of CMake as a regular user to some directory,
2. configure the build of BibleTime using the `/path/to/new/cmake` instead of plain `cmake`, and build.

**Comment by timsoftgit** [comment]
ok. I look after the bibletime slackbuild for slackware, which only has cmake 3.5.2 in stable (14.2) (although current has 3.15.2) which is why I offered a patch.
I'll have to use my patche for now, as cmake is a stock slackware package, so changing it for one slackbuild is not usually supported  (see [https://slackbuilds.org/guidelines/#other] ) second paragraph)
and I don't want to force users to install a newer version of cmake in a non-standard location just for this build. (the way slackbuilds works requires the end user to build the package themselves, rather than distributing a pre-prepared binary package)
 As soon as slackware 15 is out (hopefully early in the new year) I can remove my patch. regards, Tim

**Comment by jaakristioja** [comment]
Yes, this seems to be the best path at this moment. Thank you for providing BibleTime builds to Slackware! :-)

**Comment by timsoftgit** [comment]
my pleasure.
