### ISSUE TITLE
Need to display unlock information

### ISSUE THREAD

**Issue by gholmlund** [bibletime/bibletime#216]
There is a new keyword in sword modules that contains a message about how to unlock a locked module. The keyword is "UnlockInfo" followed by the message which can contain a link. It is in English and there does not appear to be any way to translate it. Modules with this keyword are:
NASB, NBLH, LBLA, and NA28.

The current "Unlock Work" dialog could be extended to display the message.

**Comment by jaakristioja** [comment]
We will render the text verbatim without attempting to parse any formatting syntax (including HTML tags) until Crosswire provides a reasonable formal specification for the exact syntax.

**Comment by jaakristioja** [comment]
Added the unlock information to the about text in commit a1c5848cf70d79f97b4a80c769b4d688b0b9560e.

The "Unlock Work" dialog is currently just a `QInputDialog` in [BibleTime::moduleUnlock()](https://github.com/bibletime/bibletime/blob/a1c5848cf70d79f97b4a80c769b4d688b0b9560e/src/frontend/bibletime.cpp#L192), so that needs a bit more work.

**Comment by jaakristioja** [comment]
@gholmlund Thanks!

In addition I also improved the unlock key input logic a bit in bdd113c585b484a0e4a5170eabb85e3badb3fc53 and added a password mode in commits 53eef2cb413e0a156d7fcf08d35c48925f788079 and ee538814502cdf54607cdd5111abde9de09e48b5.
