### ISSUE TITLE
BT 3.0.0 finnish translations 100 % Ready for use

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#242]
Please include 100 % finnish translations to Handbook and HowTo. I tried BT 3.0.0 RC1 handbook and it had english texts too. The 100 % reached yesterday.

**Comment by jaakristioja** [comment]
This is standard procedure according to our [release guidelines](https://github.com/bibletime/bibletime/wiki/Releasing-BibleTime#things-to-check-before-release). No special action is needed before that, since pulling the translations into git earlier would incur unnecessary and permanent costs. Please file a new bug in case we forget.
