### ISSUE TITLE
Encoding display problem in the list of the books.

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#253]
Just look the screenshot:
![encoding_issue](https://user-images.githubusercontent.com/19690477/83050383-cd448580-a04c-11ea-9ab2-72637002ba82.png)

The problem is for all the language not only French.

**Comment by gholmlund** [comment]
I cannot reproduce this. I suspect it has to do with the operating system default font. In KDE you can go to the System Settings / Fonts / General to see the font. Mine is currently "Sans Serif 10pt".

If changing the font does not help, please include more details such as the operating system version, Qt version, how BibleTime was installed (source, snap, flatpak, etc).

**Comment by LAfricain** [comment]
I use Unity on Ubuntu 18.04.

**Comment by jaakristioja** [comment]
How did you install BibleTime? What version of BibleTime are you using? What version of Sword are you using?

**Comment by LAfricain** [comment]
I compile it. sword 1.8.9 (installed with the crosswire ubuntu ppa). BT version: 3.0.0_rc1+93428d2eb083d0e3dfdf7474c2d695e3e85bafa0

**Comment by jaakristioja** [comment]
Afaik these strings come from Sword and it appears as if for some reason the ISO-8859 variants instead of the UTF-8 ones are used.

In `BibleTime::initBackends()` we have:

```
    if (!sword::SWMgr::isICU)
        sword::StringMgr::setSystemStringMgr(new BtStringMgr());
```

Perhaps Sword in the Crosswire PPA is built without ICU support? In this case `BtStringMgr` is not set to be the "system string manager", the default string manager does not support UTF-8 and the locale manager ignores the UTF-8 locale files.

**Comment by gholmlund** [comment]
@LAfricain  Have you tried this with the latest sword       1.8.903-rc3

**Comment by LAfricain** [comment]
No, do you have a deb package of this sword version?

**Comment by gholmlund** [comment]
No. I compiled and installed it using cmake.
