### ISSUE TITLE
Screen contents do not autoadjust when window size is adjusted

### ISSUE THREAD

**Issue by bugzy** [bibletime/bibletime#26]
Whenever the bibletime time window is maximized or adjusted, the contents of the displayed work do not automatically adjust and re-flow to match the new window size constraints. The dark grey area (below and to the right of opened works) in the content display window of the two images below show the problem. Note that in both cases the opened work window is maximized. This problem can be reproduced on Mac OSX (10.7) and Linux (Fedora 20 and 21).

![no-resize2](https://cloud.githubusercontent.com/assets/2759106/6047524/163d5a42-ac5f-11e4-97f5-1d19130ddbc6.png)
![no-resize](https://cloud.githubusercontent.com/assets/2759106/6047525/163ef91a-ac5f-11e4-8464-613ecef5087b.png)

**Comment by jaakristioja** [comment]
Is this the official 2.10.1 release for Windows?

**Comment by gholmlund** [comment]
The value for the window mode was initialized to zero for the first time usage. Zero is not a valid value. It was acting like manual mode (not adjusting the windows). If the user sets the window mode to some other value, the problem is gone. I have set the initial default to "Auto-Tile" to permanently fix the problem. commit 55d14cc
