### ISSUE TITLE
The pallallel reading UI is broken in 3.0.0, when showing more than 4 versions.

### ISSUE THREAD

**Issue by tiborhari** [bibletime/bibletime#268]
- It works correctly, when showing 4, or fewer Bible versions.
- It worked correctly in version 2 with 5 (or more) Bibles.
- OS: Linux Mint 20 Cinnamon 64bit
- Using BibleTime version 3.0.0, installed from flatpak
![bibletime](https://user-images.githubusercontent.com/14954677/90549982-d1310100-e17e-11ea-9a18-083ef6409cbf.png)

**Comment by tikajr** [comment]
Can confirm issue. First thing I noticed upon installing today. I like to have 5 bibles in parallel (Chinese, English, Latin, Greek, Hebrew).

I have a software development background but I'm new to Git and Open Source. Happy to contribute and try fix the bug, but wait till I get my environment set up for development on this project before assigning me to the issue.

**Comment by gholmlund** [comment]
It was coded for a max of 4 columns. Changing it to 5, 6, or 7 should be very easy. I can do that.

**Comment by youngoldi** [comment]
Great work with version 3 - thanks all.
Just would be very helpful get back more the 4 parallel Translations.
Possible 6 would be a minimum to me - more are better.
Working in a very multilingual environment that's just nice not been limited.

**Comment by gholmlund** [comment]
I am working on it.

**Comment by gholmlund** [comment]
Fix bug #268 The parallel reading UI is broken
master: https://github.com/bibletime/bibletime/commit/44f31505aca9c312cb348f6b2571a5590da29de0
stable-3.0: https://github.com/bibletime/bibletime/commit/34701af348456525d56b70e24c7ea9425a88597e

I worked quite hard to dynamically allocate the QML for each coumn. Each QML column viewer is a child of a delegate to a ListView. Delegates are dynamically created, cached, and reused by Qt. This caused numerous sizing, viewing, etc. problem and I could not make the dynamic creation work correctly.

I have coded it so that 10 columns are available.  This should take care of any reasonable case.

**Comment by youngoldi** [comment]
Hei gholmlund
thanks for this fix. 
Is there a beta version available that we could try it?
Or do we waiting for next release? 
(So with this GitHub thing's are a bit confusing to me, may be need assistance if we need to work with source code - {in my case for MacOS Catalina} - if there ist already some guide let me be linked to it)

**Comment by gholmlund** [comment]
I think I can give you an unofficial version for Mac. I will try to fix your other bug #279 first.

**Comment by gholmlund** [comment]
@youngoldi  The link below will get a test version of BibleTime-3.0.0 plus some bug fixes including this one (#268) and your other one (#279).

[http://sourcearchives.com/BibleTime-3.0.0_test.dmg](url)

**Comment by youngoldi** [comment]
@gholmlund Thanks it looks to work well on first sight. 
I will work with it in the next day, and thank God for your great work; he may bless you.
![BT3 0 test_with_HL](https://user-images.githubusercontent.com/62396046/96503417-df250000-125b-11eb-96fb-9f393eb180e5.jpg)

**Comment by jaakristioja** [comment]
Good work, @gholmlund ! 10 columns should indeed be sufficient.
