### ISSUE TITLE
Modules rearrange themselves

### ISSUE THREAD

**Issue by copenh** [bibletime/bibletime#277]
In both Mint and MX, my modules will rearrange with no warning upon startup or on a right click as for copy or select all. I have found no way to predict when this will happen. All modules appear to be intact and function normally after rearranging. It is just irritating to have to get used to the new arrangement. I can rearrange back to my "normal" in a manual fix, but this requires a lot of resizing. And the top or bottom of that module's window will be off screen and not accessible (This is a separate irritation!!!). 

Today, I turned the computer on. Last night was a normal shutdown with no apparitions. I started Evolution on the laptop and got my messages. I then did a simultaneous three start of Firefox, LibreOffice Writer, and BibleTime on my external monitor, as I always do. All three came up normal. Except BibleTime had moved SME to the left half of BibleTime's window. It used to be top right. MHC moved from left to bottom right. The KJVA moved from bottom right to top right. 

Is there a correction for this aggravation? 

I think this is a great program. Thank you for it. And thank you for your time and help. Your work on all this is much appreciated. 

Ralph  

rcopenh@gmail.com

**Comment by gholmlund** [comment]
I found a reproducible case like you describe. It only happens when using Window > Arrangement Model > Auto-tile.
1. Open 4 modules noting their positions
2. Activate one of the windows (not the upper left one).
3. Resize the main window. Windows are rearranged.

For the Auto-tile mode we use QMdiArea::tileSubWindows. For other arrangement modes we wrote our own arranger. The tileSubWindows function uses the window activation mode to determine the order of placement of the windows.

To fix this we will have to write our own arranger for the auto-tile mode.

**Comment by gholmlund** [comment]
I believe this is fixed now. I may be able to provide a BibleTime version you can test if  you cannot build the source. What operating system do you use?

**Comment by copenh** [comment]
I am using Linux Mint 20 Cinnamon. Thank you for all your help. It is
greatly appreciated.

**Comment by gholmlund** [comment]
I have created a snap of BibleTime with this bug fixed. It can be downloaded and installed like this:
    wget http://sourcearchives.com/bibletime_3.0.0_amd64.snap
    sudo snap install --dangerous bibletime_3.0.0_amd64.snap

Note: Snap applications run in their own file system so you will have to install your text modules again for it.

**Comment by jaakristioja** [comment]
@copenh Please confirm whether this fixed the issue.

**Comment by gholmlund** [comment]
Resolving as fixed.
