### ISSUE TITLE
Choose Language To Download Books Is Not Showing In Bible Time 3.0

### ISSUE THREAD

**Issue by vikramght** [bibletime/bibletime#288]
In Bookshelf Manager - Choose Language To Download Books Is Not Showing In Bible Time 3.0

**Comment by gholmlund** [comment]
I cannot reproduce this. Please tell how your 3.0 was built (snap, flatpack, source, etc.)

**Comment by vikramght** [comment]
I Am, Using Windows 10 32 bit - i install This Version On My Windows 10 - https://github.com/bibletime/bibletime/releases/download/v3.0/BibleTime-3.0.0-win32.exe

**Comment by adamoell** [comment]
I have had this issue, for several releases now. It recurs with snap installs on Kubuntu, or plain apt installs. For the last couple of years I have had to resort to manually copying .sword and .bibletime folders from one computer to another. A clean install of Kubuntu on a VM will easily allow you to reproduce this. Sadly, I am sure loads of potential users simply give up on Bibletime because of this.

**Comment by jaakristioja** [comment]
On the "Choose Remote Libraries" page of the Bookshelf Manager - what remote libraries did you select? Did those remote libraries update successfully?

As far as I know the language selection page is skipped if there are only works of only one language available from those sources.

**Comment by adamoell** [comment]
The "update remote libraries" did work, although it sat at "Getting Library List" for a long time - several minutes. IIRC, I was able to choose the FTP url for the Sword Project, but then it just hung and never showed any books to install. Having copied my old .sword and .bibletime folders, I can now access my old books - but when I try to access new books, it sits at "Getting Library List" for some time (at least four minutes) before silently crashing (all Bibletime windows disappear). As mentioned, this should be easy enough to replicate - it has been the default installation experience on a clean install of at least Kubuntu 20.04 and 18.04, and is the same whether you install via apt or snap.

**Comment by adamoell** [comment]
Worth mentioning: I didn't get any farther with Xiphos. Could the issue be with libsword?

**Comment by adamoell** [comment]
I am spinning up a new, clean Kubuntu 20.04.1 installation on VirtualBox now, and I will run through the installation and advise exactly what happens. I have set the OS language to English (UK), and it should be installed in a few more minutes.

**Comment by adamoell** [comment]
It has sat on "Updating Remote Libraries" -> "Getting Library List" at 0% for over twelve minutes. This is on a clean installation of Ubuntu 20.04.1 with a fresh snap install of BibleTime and nothing else. I am recording video of the VirtualBox screen and will keep doing so in case something happens, but surely this is already a defect?

**Comment by adamoell** [comment]
After 20 minutes I shut it down, removed the snap package and installed the built-in apt package (BibleTime 2.11.2). This is behaving the same way - stuck on "Getting Library List" with 0% progress. I will give it 20 minutes, and then upload the video.

**Comment by adamoell** [comment]
Ah! 2.11.2 got to "Remote libraries have been updated"! Took 2.5 minutes.

**Comment by adamoell** [comment]
Added "Crosswire Bible Society" (remote FTP, ftp.crosswire.org, /pub/sword/raw - no other options were available) - "Choose Languages" screen is empty. I have checked, that FTP address is valid. So 2.11.2 got one step further than the 3.0.0 snap package, but still no actual documents installed. Video of the installation and testing process is attached. 

https://user-images.githubusercontent.com/26654229/108333360-c6583700-71c8-11eb-92cd-cdf94ea35d40.mp4

**Comment by gholmlund** [comment]
It seems that you don't have ftp access. Can you directly use ftp from a terminal?

ftp ftp.crosswire.org
    Name: anonymous
    Password:
    ftp> cd pub/sword/raw
    ftp> dir

**Comment by adamoell** [comment]
As mentioned in my post above, I have no trouble at all FTP-ing to that server and path. I have tried using terminal and the Dolphin file manager, and indeed downloaded the entire folder - I mean to try local access when I have a moment. In addition, trying other protocols made no difference. This same situation obtains on MANY different networks; I am reasonably sure that FTP isn't the issue here.

**Comment by adamoell** [comment]
(base) adamoell@AdamDesktop:~$ ftp ftp.crosswire.org
Connected to ftp.crosswire.org.
220 (vsFTPd 3.0.2)
Name (ftp.crosswire.org:adamoell): anonymous
331 Please specify the password.
Password:
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> cd pub/sword/raw
250 Directory successfully changed.
ftp> dir
200 PORT command successful. Consider using PASV.
150 Here comes the directory listing.
drwxrwsr-x    2 1004     1020         4096 Nov 21  2013 locales.d
drwxrwsr-x    2 1004     1020        16384 Feb 17 08:44 mods.d
-rw-rw-r--    1 1004     1020       171144 Feb 18 08:33 mods.d.tar.gz
-rw-rw-r--    1 1004     1020       171105 Feb 15 08:24 mods.d.tar.gz.bak
drwxrwsr-x    6 1004     1020           65 Jul 20  2015 modules
-rwxrwxr-x    1 1004     1020          125 Jan 06  2020 zipup.sh
226 Directory send OK.
ftp>

**Comment by gholmlund** [comment]
Please start BibleTime from the terminal and use the debug option to save a log file.
  bibletime --debug 2>/tmp/log

**Comment by adamoell** [comment]
OK, I will have to recreate the virtual machine to do that - I deleted it after recording the video above. This will take me some effort and I don't really have time today. I will aim to get that to you tomorrow. But can I ***emphasise*** that this is a ***clean install of Kubuntu*** - no environment-specific issues. It should be as easy for you to replicate as for me, and would save a bit of to-ing and fro-ing. Nevertheless, I will set up the clean install tomorrow. Assuming I should do this with 3.0.0?

**Comment by gholmlund** [comment]
Yes, with 3.0.

**Comment by adamoell** [comment]
OK, I went ahead and set it up. As mentioned above, v3.0.0 doesn't even finish the "Getting Library List" screen - hangs on 0%.

In the log file, it looks like CURLFTPTransport connects, logs in, enters the directory OK (well, into the directory pub/sword, not pub/sword/raw), and then every second or so the log gets this line added:
CURLFTPTransport report progress: totalSize: 0; xfered: 0

I will leave it to run a while in case there are timeouts, and then attach the log.

**Comment by adamoell** [comment]
It did eventually get to the Choose Languages screen, after a very lengthy wait (> 20 minutes). But the language list box is empty. I will attach the log after Bible study tonight.

**Comment by gholmlund** [comment]
Starting with kubuntu 20.10 I did this:
  load virtualbox (from multiverse)
  install kubuntu 20.10 in virtualbox
  install snap in virtualbox
  install BibleTime using snap in virtualbox
BibleTime loaded the repositories and then Bibles without any issue.

**Comment by adamoell** [comment]
[log.txt](https://github.com/bibletime/bibletime/files/6005355/log.txt)

Here is the log - looks like it failed to get masterRepoList.conf.

**Comment by adamoell** [comment]
[log_wget.txt](https://github.com/bibletime/bibletime/files/6005362/log_wget.txt)
And here is a demonstration, from the same host, that that file is readily accessible.

**Comment by adamoell** [comment]
It seems a stretch, but is it possible that cURL's FTP is broken on (K)ubuntu 20.04 and earlier? Of these two commands:

wget ftp://ftp.crosswire.org/pub/sword/masterRepoList.conf

curl ftp://ftp.crosswire.org/pub/sword/masterRepoList.conf

the first works flawlessly and immediately, the second simply hangs without any I/O. It seems crazy that such an issue could have been sitting latent for several years' worth of LTS releases... but... I will try to build an updated cURL on the 20.04 image and see if it changes things.

**Comment by adamoell** [comment]
Not having much luck with a fresh build of cURL. I am trying Kubuntu 20.10, but that isn't really an option for me - I am committed to LTS releases. But when I point Bibletime at a local mirror of the Crosswire ftp server, it works just fine. I don't suppose there's a way to dodge the 10-20 minutes of waiting for a network timeout every time I want to install a book, is there?

**Comment by adamoell** [comment]
The apt bundled Bibletime (2.11.2) did not work for me on Kubuntu 20.10 (same issue - language list blank). The 3.0.0 snap has been hanging on "getting library list... 0%" for several minutes again, so I am not holding out too much hope for it.

gholmlund, is there any possibility that Bibletime on an English-UK installation of Ubuntu would deal with the language list differently from on an English-US installation?

**Comment by adamoell** [comment]
Right-ho, I think I may be onto something. I can get cURL to download the masterRepoList with the following command line:

curl --disable-epsv ftp://ftp.crosswire.org/pub/sword/masterRepoList.conf

Note the --disable-epsv. Without this it hangs, just as Bibletime does when trying to retrieve the same file. I am not as well-versed on FTP protocols as I once was, but it seems like a fair few IPv4 NAT firewalls have problems with EPSV FTP which cause just this hanging behaviour. A little more information here:

http://www.www-old.bartlettpublishing.com/site/bartpub/blog/3/entry/197
(search for EPSV in the text).

Or just Google "libcurl disable epsv" and see that this is a widespread issue.

Any chance you can disable off EPSV in Bibletime's call to cURL? Or at least make an option to disable it?

**Comment by gholmlund** [comment]
I am glad this is narrowed down. Thanks for that work. Unfortunately, the code that calls curl is in the sword library, not BibleTime.  I don't see any options that BibleTime could use to change sword's usage of curl. 

Have you identified which firewall is giving the trouble with epsv? Perhaps there is some configuration that could be done at the firewall.

**Comment by adamoell** [comment]
It seems to be an issue with a number of different router built-in firewalls on the market - anything which doesn't have deep-packet inspection that explicitly supports EPSV. EPSV does return traffic on random high-numbered ports; if the firewall doesn't pick up the inbound port from the datastream and open it on the fly, it just looks to the client device like no response has been received. Irritatingly, this only seems to be done for DIR and FETCH traffic, so the FTP client is able to connect, login and CD - and so cURL doesn't fail back to normal PASV mode. The firewall workaround is... open all TCP ports in range 1025-65535, which wouldn't really be sane.

Would it be possible to modify Bibletime so that you can specify a local modules directory before it tries to connect to remote servers? This would presumably also be useful for the persecuted country use case. I'm thinking in the Bookshelf Manager's first screen, you could add an additional Bookshelf task:
* Install additional works (uses internet)
* Update installed works works (uses internet)
* Install additional works (using local repository)
* Remove installed works 

Another option would be to mirror Crosswire's repository on an FTP server that doesn't do EPSV, forcing cURL to negotiate a different protocol (probably PASV, which works fine). This is what I will probably end up doing for my users, but it STILL means the lengthy timeout at the Updating Remote Libraries dialog, unless BibleTime allowed you to specify a target server before doing its own thing.

Probably the best answer in the long-term would be for the libsword authors to use a protocol which is more sane than FTP, which feels like a bit of an archaism really. I will see if I can raise a bug against libsword somewhere. Failing this, it seems likely that many, many prospective users of BibleTime are just going to give up on the great software you produce.

**Comment by gholmlund** [comment]
You make it seem like this is a very common problem. But, this is a problem for all applications that use the sword library. I don't believe the ftp code has changed for a long time. I have not previously seen a problem about ftp and epsv. It seems like it is not very common.

The ftp path for getting the masterRepoList.conf is hardcoded in the sword library, so BibleTime cannot implement a alternate repository. It would be possible to edit your /etc/hosts and give ftp.crosswire.org a different ip address.

Also, I don't see a runtime way to make libcurl not use epsv. It can be compiled off.

**Comment by adamoell** [comment]
It's easy to disable in libcurl:
https://curl.se/libcurl/c/CURLOPT_FTP_USE_EPSV.html

In fact I downloaded the libsword source and built it with the change, but it produced a library version 1.9.0 which BibleTime didn't seem to like :-( (wanted 1.8.1). I suppose I could try and build BibleTime as well, but that will have to wait - I have already spent a good few more hours on this than I can really afford this week :-)

I actually do think that this is a reasonably common problem, though not maybe *very* common. And, yes, it has been a problem for me for years now - I have literally hand-copied over a .sword folder from some time back in 2010 or thenabouts to keep it going with each new installation.  It looks like EPSV became cURL's default around 2012/13-ish... and over the years I have noticed quite a few others ask about the issue, but because they just get told "can't replicate" I suspect they give up. At a rough guess, maybe one in four potential home users is going to be affected? As you say, it affects all applications that use libsword - and as I mentioned previously, the same problem is there with Xiphos. 

There are over ten thousand hits on Google for "libcurl epsv hangs" - and that's just the people who were sufficiently tech-savvy to figure out the issue. I appreciate that it's convenient to blame the user's environment when you can't replicate the issue easily, but when it happens on a *clean installation* in a very common network setup (I have a Plusnet Hub One, same as hundreds of thousands of others in the UK, and this is by no means the only affected router), I think it's unfortunate not to tackle the problem , especially when it's a one-line change (see https://curl.se/libcurl/c/CURLOPT_FTP_USE_EPSV.html) in libsword's src/mgr/curlftpt.cpp. 

The hosts file plan you suggest is what I am busy implementing. But it means I have to maintain a local mirror of the whole repository, which is an enormous burden - it's been downloading the mirror for hours, and is running into tens of gigabytes. Fortunately the LFTP mirror tool uses a sensible FTP library! But to be honest, hardcoding an FTP location into a library is about as bad as bad ideas can get - and, nearly as bad, is using *FTP*, a protocol which is fabled for security issues and firewall nightmares, to retrieve a simple text config file!

I appreciate that these are libsword issues rather than BibleTime issues. But they certainly impact BibleTime, and they certainly mean lost users. I have sent an email to the SWORD developers, but I suspect that your name might well carry a bit more weight with them if you were to email them as well. Simple suggestions like:
1. parameterise the masterRepoList.conf location - why not let it be local?
2. parameterise the default cURL FTP settings
3. maybe using FTP to manage core config settings is not a great architectural choice in 2021.

At any rate, I have a workaround, even if it is expensive and burdensome. I will profess a little disappointment that 'leave it to the end user to run his own ftp.crosswire.org mirror' seems to be the result when such a trivial solution has been found for an issue which has been causing users trouble for years.

**Comment by adamoell** [comment]
According to https://www.crosswire.org/sword/index.jsp, the last official release of The Sword Project was 23 December 2017... is it just that libsword is a moribund platform?

**Comment by adamoell** [comment]
I have had a further thought. The actual bookshelf management stuff seems fairly straightforward. I could maybe put together a little Python 'external bookshelf manager' which could control the contents of ~/.sword without reference to libsword. Presumably as long as the directory structure/content is the same, BibleTime would be happy enough to use it? Can you see any issue with this as a reasonable workaround? Perhaps it could even have a REST API wrapper around all the nasty FTP stuff.

**Comment by gholmlund** [comment]
Yes, the directory/file structure for each module is all BibleTime needs.

Sword 1.9 was released Nov. 2020.

**Comment by jaakristioja** [comment]
I appreciate your ideas and willingness to help in action, but regarding this issue it is really libsword which should be fixed. And that is extremely hard, if not impossible. Adding any more Sword workarounds to BibleTime would make matters worse, and I would not like to introduce new dependencies like Python. 

Closing this as there does not seem to be anything reasonable we can do to fix it in BibleTime code at this point.
