### ISSUE TITLE
NA28 module unlock

### ISSUE THREAD

**Issue by bodiro** [bibletime/bibletime#291]
I can not unlock NA28 module by Deutsche Bibelgesellschaft though I have a valid key that works in other programs. I tried several times with different intallations in Manjaro Linux and flatpak.

**Comment by gholmlund** [comment]
If you are doing copy/paste make sure there are no space characters at the beginning or end of the key.

**Comment by bodiro** [comment]
Crosswire says, the latest Sword is necessary. The key works in Bishop. I avoided space characters. Still not unlocking properly.

**Comment by jaakristioja** [comment]
What version of BibleTime are you using, what operating system and how did you install it (system package, snap, flatpak, ...)?

**Comment by bodiro** [comment]
Version 3.0.0 on Manjaro Linux KDE as a system package.

**Comment by jaakristioja** [comment]
I think this has to do with the broken key "personalization/de-personalization" logic [introduced](https://github.com/bibletime/crosswire-sword-mirror/commit/70123abff253c06c237de65b90b1b48f34d45051) Sword 1.9.0. As far as I understand, it was introduced as a kind of security feature to make Sword more attractive to publishers who want to limit distribution of their works by encrypting them. However that feature provides almost no security and it currently also breaks compatibility between modules with different types of keys and different versions of Sword.

If your unlock key consist only of groups of Latin alphanumerics separated by dashes, then that is a likely indicator that you have a personalized key, but are using an older version of Sword. If you are using a Sword 1.9.0 or later you probably have a non-personalized key.

I'm guessing that on your computer you're using Sword 1.8.1 from [system package](https://discover.manjaro.org/packages/sword), but Bishop on your Android device seems to work because it has Sword 1.9.0 or later bundled within.

I don't think I will do anything in BibleTime code to work around this broken anti-feature in the Sword library, except perhaps drop support for encrypted modules entirely if they succeed in making it even worse. I believe it is so broken, that there is no simple fix solution to this, not even in Sword, so we just have to live through. I suspect the Sword developers don't want to take the initiative to fix this either.

I'm sorry for not having good news.

The simplest solution would be to wait for Sword 1.9.0 in Manjaro (and perhaps contact your vendor to speed things up). 

You could also somehow try to use the ["(de-)personalization" algorithm](https://github.com/bibletime/crosswire-sword-mirror/commit/70123abff253c06c237de65b90b1b48f34d45051#diff-5cad936e05f4df34b5b542825fdc0ad604d8ea9fac014a43e9ca27226bd69a1aR168) on your key to get a "de-personalized" version of it you can use in BibleTime with older versions of Sword. Note however, that BibleTime stores the unlock key in the configuration, and if you later upgrade to Sword 1.9.0 or later you might have to manually edit your BibleTime configuration files to be able to access the encrypted module.

Closing. Please reopen this issue if there is good reason to believe that this is not related to this unlock key personalization thing. I'm sorry for not having good news.

**Comment by bodiro** [comment]
Thank you for caring. I'll wait for Sword 1.9 in Manajaro.

**Comment by haggkoos** [comment]
I'm not sure but I will ask: Can this issue be re-opened?
I have the same issue as the original poster.

`Xiphos 4.2.0 (gtk3 webkit2)` NA 28 unlock works
`Bibletime 3.0.0 & 3.0.1` NA28 unlock does not work
`Sword 1.8.900` both programs are running off of the same Sword version (same computer). 
System information: Linux Mint 19.3 Cinnamon 64 bit

Does this mean that there is something other than the Sword version that is causing this issue?

**Comment by jaakristioja** [comment]
> Does this mean that there is something other than the Sword version that is causing this issue?

Yes. See my above comment and [this sword-devel mailing list thread](https://crosswire.org/pipermail/sword-devel/2019-October/047372.html) for details.

Unfortunately, this is not only a technical issue, but also a cultural issue, and perhaps even a conflict between the developers of Sword and BibleTime.

**Comment by jaakristioja** [comment]
One can use the following C++ program to convert new keys to the legacy format, which I think might be can be used to decrypt the modules in BibleTime. Just replace the `<KEY>` on the first line with your new key and execute the program, e.g. on [Compiler Explorer](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAAbADspAAOqAqETgwe3r56KWmOAkEh4SxRMQm2mPYFDEIETMQEWT5%2BXJXVGXUNBEVhkdF6CvWNzTltQ929JWUSAJS2qF7EyOwcyAgNANRoDEObAFSbIQDuANKYAJ6bJgDMACLXZma3bqfYAJq32ObPN1YaAEETICAPT7YEAw4eJIXYh4YAIAibLgATjRAFozBouDdNm5iKkFAB1PDETCbCx4CL0TZCVDIPCYAhXCCIghJEAgkHHHkAOmQBIUCmOpMwvJIwFmEMOm1lsvxhJJZIpVJpdIZTIu0rlcuUvM2AHl9RZUKpNmYAKxmAAc2p1mwAKpgWElMKRNgCAFqy61W60aTF%2B6Xah0IPAKTZJAnAYisTbhzZUMnkhSoKgEY4NTC3CybC6LbaGTZk/BDOERLwEcmETaGdAgkibFgYPBUK6EbVeBhYYibAgIclV4gsCNpvsDzYAcVCcinjGiYk2yi81LwyE2QRWu3JTAjSRXtHDA/QmwiV372cBhwAYsnaWmM1nNtfFt2mDVNgA3aJpATm3nBlejphnu0axiw8YRqWBDlpWmAnsE47kggqCuuO77xkiIq0LQp7kl4ShUF4tDuhWBDakSACSDoABIGnIDoeqE7ybESAIAErsQCoQOp8fybCK/aLEimDfgwSHxi6h7wQJDSxoIVxptqACy2DsW4NHcQ6AIWJRATUSxjbXtRoTYEIQjPga7EekuHEOpRbhyAEHFLnI7HKAaQjYPqtKYIOE7TnI2qTvOsa4cuq7rpujBKImjbNsqWD1HQCgAVe0oghCWVmDcwTIN4WDXDcbhlsEwBfNluUMPlXiFS8LBMEkFWAhC6xbAYBAKCYFpWBaDy3P18T/ACcpgBwERje6Y3IJNmxjZgs1jUwi0cFQK3ACteArdoK0ANYrbQk0QqNHAICtLArUkK0AI4rRYK3ECtNEragK0KCtBBHYCJ0OitXgrccK2qCtFwrQCK3oCtbgrXcK0AF5fSNspjdgK3XitlErQAUitpwrZOK0BCtoQrQaK3xIjJ3KCtACKK3KSt7ErUIK1yCtABqK1EitAAaK3vJTyMcCiK0aCtXArWYK2eitNwrbEK2SCtDArdagtzRwn4rRaY1ZfEdw5llgJDOgIAgKVRh9qgASYMATDIBc5wXBAJtmxbwCnl4VCzNcQ3HbKrsgA1TXFW1ZDxoIXzbBsxA0buCCG99sr8L2EDBEieBFQ8Gg5vGRVuJssS/Lm1jWHgPth3HCgJz1HVdT1eDdQbfVZ/GidAknmyB%2B7Xe2/XFgWk37dyunvfAOJA2bDnfz%2B3Fqddmk48yaPmeT9Puar8VntULyaRw5gEA%2B%2BYsTH2PE9b4P/Gl5Y5e%2B8N9rxlQmwQBWVDdZSTdZ5PY3omNR%2BWNYJQ49h72iqLFIB/cgEME/qXe42936Nz6iA32BtO7dxgmVYsmAFDEXIjPNBBBTbmwwZbdYu0hA%2BFbhA9%2Bkgh74KRo/Z%2B1Ceq0L6rvPA%2B9D7502BaH2zCLCsLuLyMke8D7SA1hrKU9C5Qp2fivVu6884vE2LQq%2BACb5Hz9p3Eeghtg4IgmvZBMjGwQAXvCEICFdHaAUbnaxyj%2BGIKEaIrhx9T52K3vwnObDnFSJLuoiw2hNH3wfvaMOmwNjV1bpXeO78HFDx6toeJBtpEhJ1GE1AEQiIKCrggKJMccmxL7u/LxzcAnmAtJ4pu7DOFSiQUglJqT7QZKyTk1uETcnWDkUVa8mxmkEVaSAKevjZ6NLlH07J8dHiXweEXIxqTWxyL4UUhu8Sykt0nnXd%2BEBaACElOMgp9TgmjOQPox4Vg4HtLmSgkZAdlkCNWY41umyeonJ8OU2ZhybmMIgCI3B1SD6zB9r82gSJYH9SeOiH4VzgWgoAXAiAYAwCbx6VCp4mxBlxLYcgAA%2BmWQ%2BwzO4mH1rPMkBAljiQgGQihEFEWT34YIo%2BNwemv3RVgnBIL25EtQR3IEOU8oFXJC8JwZZMCsGagCUeDVgguK0QwwOaBKz52UT8G2dsHabF2pcQZPwlVbyIKq%2B2jtLgQBOE7Rlbh7GELNq4WgnLiWAg4PMWgnALS8D8BwLQpBUCcAtf4ruixliCpyjwUgBBNCOvmLtEANwbi8hjfGhNibYj6E4JIN14avWcF4AoEAGhQ3hvmHAWASA0AujoNEcglBS1JHLTEYAUgzB8DoEOHNL8M0RGCA0C4nAQ0duYMQC4BoIjaEwA4HtvBS1sEEAaBgtBu0et4FgCswA3BiFoDm7gi7nSGGAOIBdpB8BkgcHgb8G7PWYFUKOuCGb05VAzYeCIsYB0eCwBmjBLBx2kG/MQCIqRMB3G3UYQ8RgC18AMMABQ7NGTHANK6d1Ib%2BCCBEGIdgUgZCCEUCodQ%2B7dBtAMCB0w/j9BUhzZAeYqEagbvRAaMwmx0REjXXRokF6YJMF4Kgb9cIsCkcPu0UdNQXDdlGK0UggRgh9FKAMNoeR0gCGE7kVIsmGBTH6DEcYVR%2BOdGGE0TwLRBgaePQILojQVOSbU7YbT8nxjadMzMLg8xUxLBWHMFNHBXWkHdZ671HBNiqGtLEdEsRJCbGAMgdcUheS0YgLgQgjZzA3Hs7wMNC7AWkCjTGuNiassxuTc6jgaaPMZu89m3N%2BaUukCLYgEAwl9wEErZS1AZb6DEFCKwVYfmAtBZC2F5EkhIu8HgrFrjehEPCFEOINDo3MNqAzbh0gxxYwck3U6l16b93eYNJWWrvSn4dcC8F0L4W%2BtRY8E16IjwEuzCSwWyN0bY3Zey65grnn2NZtsKV5LWhUt5bMGtrzb3PsRq/T%2BDIIBJBAA%3D%3D%3D).

<details>
<summary>Source code for key conversion</summary>

```c++
char const * newKey = "<KEY>";

/*
* Copyright 1999-2013 CrossWire Bible Society (http://www.crosswire.org)
*      CrossWire Bible Society
*      P. O. Box 2528
*      Tempe, AZ  85280-2528
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by the
* Free Software Foundation version 2.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
*/

#include <string>
#include <map>

char lats[] = {
   'b', 'c', 'e', 'a', 'f', 'g', 'i', 'j', 'k', 'l',
   'h', 'm', 'p', 'q', 'B', 'r', 'H', 'o', 's', 't',
   'T', 'u', 'w', 'x', 'y', 'A', 'd', 'C', 'D', 'z',
   'E', 'F', 'I', 'J', 'K', 'G', 'L', 'N', 'O', '7',
   'P', 'Q', 'M', 'R', 'S', 'U', 'V', 'W', 'X', 'Y',
   '9', '0', '1', '2', 'Z', '3', '6', '4', 'n', '8',
   'v', '5'
};

std::string toLegacyKey(std::string buf) {
   std::map<char, int> charHash;
   for (int i = 0; i < 62; ++i) charHash[lats[i]] = i;

   std::string segs[5];
   int segn = 0;
   for (unsigned int i = 0; i < buf.size() && segn < 5; ++i) {
      if (buf[i] == '-') ++segn;
      else segs[segn] += buf[i];
   }
   std::string result;
   std::string chkSum = segs[4];
   if (segs[4].size() < 5) segs[4].resize(4, ' ');
   for (int i = 0; i < 4; ++i) {
      int csum = 0;
      for (unsigned int j = 0; j < segs[i].size() && j < segs[0].size(); ++j) {
            char hash = charHash[segs[i][j]];
            char obfusHash = charHash[segs[0][j%segs[0].size()]];
               obfusHash = hash + (i ? obfusHash : 0);
               obfusHash %= 62;
            if (i) segs[i][j] = lats[(long)obfusHash];
            csum += hash;
      }
      segs[4][i] = lats[csum%62];
      if (result.size()) result += "-";
      result += (!i ? "" : segs[i].c_str());
   }
   return (chkSum != segs[4]) ? buf : result;
}

#include <iostream>
int main() {
   std::cout << "Legacy key: " << toLegacyKey(newKey) << std::endl;
}
```

</details>
