### ISSUE TITLE
Cannot change the size of the default font

### ISSUE THREAD

**Issue by dkuteynikov** [bibletime/bibletime#292]
BibleTime 2.11.2 in Ubuntu 20.04.1 LTS.
Go to Settings -> Configure BibleTime... -> Fonts
The size column is empty. Only if I select another font, the sizes appears.

![fontsize](https://user-images.githubusercontent.com/63711427/104850646-e7dbaf80-58f8-11eb-8f3f-ca7a99fe4d1d.png)

**Comment by skyblue002** [comment]
I have a similar problem. I'm going to post some details about it, in case it helps the developer to track down the problem, as it might be caused by a similar issue.

I'm in Manjaro Nibia 20.2.1 running Cinnamon desktop environment and BibleTime 3.0.0. For some of the fonts, the size numbers don't show up, for others they do show up, but when I click on them and hit "Apply," the changes aren't made to the text. If I go to Settings > Configure BibleTime... > Display, and change the display style to another .css, the font size can change, but it doesn't seem to alter the font face at all. I tried running "bibletime" in the Terminal and it gave me some errors about not finding murrine Gtk engine. I installed it and while the error went away, the issues with changing the font face and size weren't solved. There are no errors now when running BibleTime from the Terminal, even when the font face/size fails to change after hitting "Apply."

**Comment by jaakristioja** [comment]
I replaced the custom font chooser widget with `QFontDialog`, and changed slightly amended code in places where the font is used.

Commits af7347595876076aee471ca335f4df1cd0047d62, 9cdd8dcef93a147352bc53572a8ce1d7e9772a43, f013da5d91ea0e1e3a6b1850bec947746ee9ec8e and 8105e034a878337242844801c5f21a5e8e5b566a in the master branch. 

Although this can be considered as a "feature change", I believe there were other bugs lurking in the `BtFontChooserWidget` class, and since we don't do releases very often, it seemed reasonable for me to do the changes in the stable-3.0 branch as well (commits 348dc595d47d1daaf3236c24e11503ddbe929d3b, 6c119f519380adb304022ee4897fb6acfb2b10d3, 6c1532bc91289e4b4d7a75c01cd33f733a2ebbb3 and ad4036b1a253ceaeb7c6053ad1fa44bad344a9e1).

So this will only be part of BibleTime version 3.0.1 and later, since we don't have the resources to maintain older versions.
