### ISSUE TITLE
Request App Image of BIbletime 3.0

### ISSUE THREAD

**Issue by haggkoos** [bibletime/bibletime#293]
Hello!
Thank you for a wonderful program. 
I am currently using Bibletime 2.11.1 on Linux Mint 19.3, this is the version available in their repositories. Version 3.0 is currently not available, also at the PPA by Crosswire: https://launchpad.net/~pkgcrosswire

Would it be possible to build an appimage of Bibletime 3.0? This will be able to be used in many Linux distributions. 

I am aware that Flatpak is available but on my system asks for too much space (800MB download). 

Thank you for you help,
Koos

**Comment by jaakristioja** [comment]
If it helps, I believe we also have a Snap package of BibleTime and it might be possible to install that on Linux Mint as well.

> I am aware that Flatpak is available but on my system asks for too much space (800MB download).

That is probably because it needs to bundle all libraries used by BibleTime. An appimage package might be of roughly the same size.

PS: We're also considering the creation APT repositories for Debian-based distros.

**Comment by haggkoos** [comment]
Thanks for the information. I think APT repositories would be appreciated by quite a few users. (Linux Mint has the ability to handle snaps, though not by default) 
I was able to build from source, so happily running 3.0 now :)
