### ISSUE TITLE
Bookshelf doesn't remember whether it'd been expanded or not

### ISSUE THREAD

**Issue by jaakristioja** [bibletime/bibletime#3]
From the old (bugs.bibletime.info) and older (SourceForge) bug trackers, the original bug report by alvanx (alvanx) - 2011-01-14 12:13:54 PST:

Bibletime 2.8.0, Qt 4.6.3, openSUSE 11.3: The bookshelf doesn't remember if one or more categories had been expanded the last time BT was used. It always starts collapsed. It used to, so I assume it's a bug.

This is something we didn't reimplement when we switched to the new bookshelf tree model view framework.

We could try to implement it similarly to the solution described at http://stackoverflow.com/questions/3253301/howto-restore-qtreeview-last-expanded-state

**Comment by gholmlund** [comment]
The Bookshelf Manager has change a lot since this was written. It does remember the remote sources and languages previously used. The only thing to expand would be the category. I believe it is best to NOT expand the categories. If they are expanded there is a long list of works to scroll through and it is hard to find the categories. I suggest we close this issue.

**Comment by jaakristioja** [comment]
@gholmlund This is not directly a bookshelf manager bug, but also affects the bookshelf dock widget, which is how I understand this issue.

**Comment by gholmlund** [comment]
Bookshelf expansion paths are saved/loaded from bibletimerc.

**Comment by jaakristioja** [comment]
Thank you! I confirmed it works. :-)
