### ISSUE TITLE
Toolbar, bookmarks and books

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#302]
I tested toolbar icons bookmarks and books. First when I started BT 3.0.0. there appeared bookshelf window and magnifying glass window. But then I pushed the two icons and got the BT working such kind that only one of them can be on screen.

If I have bookshelf opened and I push bookmarks, it doesn't appear to screen. And then when I push again bookshelf button, it disappears and bookmarks appears. As if the bookshelf had covered the bookmarks.

And now the Bibletime starts only one window of bookshelf or bookmarks. Not both. Maybe this is not a bug. It's feature. I think that it is good that it has more area in my 27" monitor. Those does not affect to opened Bibles right side. And if I perform a show bookshelf in menu, that doesn't work. And if I perform a show bookmarks when bookshelf is opened, it doesn't appear.

**Comment by gholmlund** [comment]
The bookmarks, bookshelf, and MAG windows are docking windows which means the user can move them to different locations. When BibleTime is first started they are placed at the left with bookmarks and bookshelf on top of each other. There are tabs that choose which is currently on top. The toolbar icons for these just toggle the visibility of each docking window.

If  you want to move them drag them from the top of a docking window and you will dynamically see how the docking windows will be if you drop them.

**Comment by ilkant** [comment]
Ooh! Wonderful. I took mag outside BT windows. Thanks.

**Comment by ilkant** [comment]
When I moved mag outside BT, it does not copy text from Bible to mag.

**Comment by jaakristioja** [comment]
@ilkant We really appreciate you taking all the time to find these issues. Thank you! But on the other hand we are quite overloaded us with issue reports and with very limited resources to develop BibleTime. @gholmlund and me are the only developers currently working on this legacy project. And we know that there were more bugs in BibleTime than we are able to fix even before you came along. If you want to help more, would you care to lend a hand and try to fix a few of these bugs yourself? :-)

**Comment by jaakristioja** [comment]
I'm having trouble understanding what the exact issue is. Or are there multiple?

**Comment by gholmlund** [comment]
I did some testing of the docking windows (MAG, Bookshelf, Bookmarks). I found several problems when operating under Wayland. These problems did not occur under X11. 
1. I was able to undock a docking window, but it would not redock.
2. When undocking a docking window, it immediately jumped to the center of the BT main window.
3. I was able to undock a docking window and have it disappear. Toggling its "View" menu did not fix it. Restarting BT did not fix it.

Since these issues only happen when using Wayland, they must be either a Wayland or Qt issue, not BT.
I am closing this issue. If there is still a bug either reopen this issue or better yet create a new issue with a clear description.
