### ISSUE TITLE
[BUG] hbo (Hebrew, Ancient) language code is not properly supported

### ISSUE THREAD

**Issue by tsbockman** [bibletime/bibletime#327]
**Describe the bug**
The "hbo" language code is not properly supported: it is missing a full human-readable name, such as "Hebrew, Ancient".

Not only is this confusing, but it also breaks the custom font settings, apparently because the configuration file tries to use full language names instead of their short codes.

**To Reproduce**
1. Install the OSHB 2.1.2 module.
2. Go to Settings > Configure Bible Time > Fonts.
3. Try to set a custom font for the "hbo" language.
4. Observe that the font doesn't actually change, even after hitting "Apply" and restarting the application.
5. Note that the "bibletimerc" configuration file "[fonts]" section has no entry for either "hbo", "Hebrew, Ancient", etc.

**Expected behavior**
"hbo" should have a full human-readable name, "Hebrew, Ancient", like other languages do. Also, custom font settings should work even for languages without a known full name.

**System information (please complete the following information):**
 - Kubuntu 21.04
 - BibleTime Version 3.0.0 (via the package manager)
 - OSHB 2.1.2

**Comment by jaakristioja** [comment]
I'm not entirely sure we can fix this for 3.0.1, as this would involve some changes to the configuration file format.

**Comment by jaakristioja** [comment]
Fixed in master mostly by 98e0011a5856a94540921daa043840e23098fd0b. I'll try to backport to stable-3.0 as well.

**Comment by jaakristioja** [comment]
Fixed in stable-3.0 branch by cc9d9e617 and related commits.

I also added commit 7c36f85f2c26cac02ffd99add9c06452b234ca51 to force configuration files of users of 3.0.1 to store fonts for languages also based on the abbreviation. We probably need to figure out a better migration logic in the future, but in case we can't come up with a totally streamlined migration mechanism for this, this change might help to minimize any negative UX impact caused.

**Comment by jaakristioja** [comment]
Actually, I did not yet provide a human-readable name for hbo. Reopening.

**Comment by jaakristioja** [comment]
Ok, this fixed by commits 0a56a9202 and c616e2182 in master (commits a356c5eab and 9a243fe7a in stable-3.0). So now BibleTime attempts to retrieve the full names and translations from Sword.

However, for languages like `hbo,` Sword provides "Ancient Hebrew" instead of "Hebrew, Ancient", so I also added custom translations for the language `hbo` in commit 7ee4601fe (e434cf332 in stable-3.0). Since this change introduced a new translatable string, BibleTime translators might not be able to translate it in time for 3.0.1, but I guess that is still better than only displaying the language code.
