### ISSUE TITLE
[BUG] Still cannot see apocrypha in list of books

### ISSUE THREAD

**Issue by aario** [bibletime/bibletime#377]
**Bug description**
Apocrypha books are not being shown in the dropdown menu. Should I search anywhere else for them?
I have already read through bug report #12 and I don't know why they say it is fixed.

**Steps to reproduce**
1. I compiled verwsion 3.1.0_dev from source using:
```
CMAKE -Gninja && ninja
```
2. Removed `~/.bibletime` and `~/.cache/bibletime` folders.
3. Had KJVA already downloaded to my `~/.sword` folder.
4. Started bibletime.
5. Opened KJVA
6. Clicked on dropdown menu for list of books.
7. There is no apocrypha.

**Expected behavior**
The drowpdown menu must show items like Wisdom of Solomon or other Apocrypha books.

**Screenshots**
![image](https://user-images.githubusercontent.com/11817199/156349072-092fdf5e-2615-42c2-8615-48b1b5ba388b.png)

**System information:**
 - OS and OS version:
 ```
 PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
 - BibleTime Version 3.1.0_dev
 - How BibleTime was installed: compiled from source code
 - Versions of modules related to the crash (if known)
 - (If compiled from source) Sword Version: SWORD library version 1.9.0
 - (If compiled from source) Qt Version: Qt toolkit version 5.15.2

**Comment by aario** [comment]
Deleting the KJVA book and downloading it fixed the issue.

**Comment by jaakristioja** [comment]
@aario I suspect this might be caused by some known bug(s) with parallel works. Might it have been the case that you first opened some work(s) without apocrypha and then added KJVA as a parallel work, and then closed the other parallel works, leaving only KJVA? In such cases the list of available books might continue to "stick" to that of the previous first parallel work. A partial workaround might be to open a new subwindow with KJVA as the first work.
