### ISSUE TITLE
[BUG] Menu shows lower on screen and not at the top with certain gtk themes

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#381]
**Bug description**
When using numerous gtk themes (e.g. Arc-theme) when you click on the one of the menus (with the exception of the Help menu), the menu shows further down on the page.

**Steps to reproduce**
1. Install Bibletime
2. Click on 'File' menu

**Expected behavior**
The menu should show up as all other menus, that is, top aligned with the menu bar.

**Screenshots**
![Screenshot-2022-05-07,11-46-41](https://user-images.githubusercontent.com/7609728/167249120-ffe651f6-770b-4ecd-a5b1-551e09c03206.png)

**System information:**
 - Fedora 35 Wayland
 - BibleTime 3.02
 - Flatpak

**Comment by jaakristioja** [comment]
I don't consider this to be a bug in BibleTime code. I believe this is infeasible for BibleTime developers to fix because the bug most likely hides somewhere in the clue code between Qt and GTK themes, and a bug should be filed to these instead.

Alternatively, please compile and run BibleTime from source code and see if that also suffers from the same problem. If it doesn't, the flatpak packaging might also have something to do with this.
