### ISSUE TITLE
[BUG] v3.0.3 Bookmarks Display error

### ISSUE THREAD

**Issue by troypulk** [bibletime/bibletime#394]
**Bug description**
Click view in menu bar > show bookmarks and/or toggle button in main tool bar, bookmarks window does not open.

**Steps to reproduce**
1. Click view in menu bar > show bookmarks and/or toggle button in main tool bar, bookmarks window does not open.

4. See error: bookmarks window does not open then Mag and bookshelf freezes.

**Expected behavior**
bookmarks window opens

**Screenshots**
See attached

**System information:**
 - OS and OS version: Solydx 5.17.0-1-amd64, SMP PREEMPT Debian testing 5.17.3-1 (2022-04-18) x86_64

 - BibleTime Version: 3.0.3-1 Debian Testing - 
 - How BibleTime was installed: from system packages - 
 - Versions of modules related to the crash (if known)
 
**Additional context**
output of `bibletime --debug`

Debug: return an empty key for 05624

![Screenshot_2022-06-04_13-16-22](https://user-images.githubusercontent.com/26691252/172031141-128f749c-cf39-427c-ab40-98a550ccfff1.png)

**Comment by gholmlund** [comment]
I believe there was a problem with docking the Bookmarks window. It can be docked several places. Can you rename or remove the $HOME/.bibletime/bibletimerc file. This will bring back the default docking position.

**Comment by troypulk** [comment]
Thanks,
That did it, is this being worked on?

Another question, How do I uninstall 2.11.2? it and 3.0.3 are both installed, I thought that when 3.0.3 was installed it would of over written 2.11.2.

Thanks

**Comment by gholmlund** [comment]
Docking behavior is handled by the Qt library. We probably cannot do much about this.

Yes, 3.0.3 should have removed 2.11.2. This is handled by the person creating the Debian package. We don't create this package.

**Comment by troypulk** [comment]
Is there anyway to remove 2.11.2?

What if I uninstall 3.0.3, will that remove 2.11.2?

Thanks

**Comment by gholmlund** [comment]
It seems like installing 3.0.3 might have over written some files of 2.11.2. I would think that uninstalling both and reinstalling 3.0.3 would be the best way.

**Comment by troypulk** [comment]
Thanks, I'll give that a try.

**Comment by jaakristioja** [comment]
If you installed something using `make install` as root, it probably got installed under `/usr/local/` and you have to remove it manually. We don't currently provide an `make uninstall` command (or plan do to so in the future), but if you're willing to experiment, you could try `make uninstall` the approach described in the [CMake FAQ](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake).

Other than that, as already stated the original issue appears to be some bug in Qt or elsewhere, and there is there might not be much we can do to help. The screenshot you included shows some rendering artifacts, so if it is only the dock widgets which "froze", you might as a workaround also try to interact with them anyway, e.g. resize them. Sometimes some Qt components may just appear frozen due to rendering, but are otherwise fully functional.

Closing.
