### ISSUE TITLE
[BUG] Language set to Russian even though system default language is English

### ISSUE THREAD

**Issue by danzek** [bibletime/bibletime#414]
**Bug description**
Opens with incorrect language settings (Russian, not English).

**Steps to reproduce**
1. Install BibleTime in Applications folder
2. Open BibleTime
3. Opened for me in Russian language. This is a language/keyboard I have installed but my computer is set to English as the main language. Unable to change it.

**Expected behavior**
The program should use my system language.

**System information:**
 - OS and OS version: macOS 12.6 Monterey (M1 / Apple Silicon)
 - BibleTime Version: 3.03 release DMG from https://github.com/bibletime/bibletime/releases/download/v3.0.3/BibleTime-3.0.3.dmg
 - How BibleTime was installed: copied to Applications, com.apple.quarantine attribute manually removed

**Additional context**

My language settings are correctly set to English and I do not have this issue with other applications, including other Qt applications. The `CFBundleDevelopmentRegion` key is set to `en-US` in the application's `Info.plist` yet it still shows up in Russian. I've also confirmed my macOS language settings are correctly set to English in the GUI preferences as well as using `languagesetup` CLI utility (`en`). My system language has never been Russian, I just have the keyboard installed.

For further testing, I compiled a simplistic Qt CLI app to output the value of `QLocale().name()` as [that appears to be how BibleTime is fetching my language/locale](https://github.com/bibletime/bibletime/blob/ae44428a31ed457c2cf0941efb0b1ba6f06bc353/src/frontend/settingsdialogs/cdisplaysettings.cpp#L180).

Code:

```
#include <QLocale>
#include <QDebug>

int main(int argc, char *argv[])
{
    qDebug() << "QLocale name: " << QLocale().name() << Qt::endl;
    return 0;
}
```

Output:

`QLocale name:  "en_US" `

It appears to be correct. However, I tested using Qt 6.3.1, not 5.15 which I believe is what BibleTime uses. I imagine the result should be the same, though.

English is my system language and the top one displayed:

<img width="339" alt="English as top language" src="https://user-images.githubusercontent.com/6609869/196340160-bb05a026-35a2-41d3-8704-11bb6ca009f1.png">

**Comment by gholmlund** [comment]
We use QTranslator::load() to find the correct bibletime_ui_<locale>.qm file. I debugged into this function to see what it does.

First it tries to find the locale en_US by looking for a bibletime_ui_en_US.qm file. This fails because this file does not exist.

Next it gets a list of available ui languages using QLocale.uiLanguages(). On MacOS this appears to be based on the preferred languages dialog(above). So it tries en_US again and fails. It keeps going through this list and finally finds the bibletime_ui_ru.qm file. So, the BibleTime UI appears in Russian. 

NOTE:  copy bibletime_ui_en_GB.qm to bibletime_ui_en_US.qm and you will have a English UI.

FIX; It seems we need to add a bibletime_ui_en_US.qm file

@jaakristioja  Any thoughts?

**Comment by danzek** [comment]
Copying `bibletime_ui_en_GB.qm` to `bibletime_ui_en_US.qm` in `/Applications/BibleTime.app/Contents/share/bibletime/locale` resolves this issue for me.

**Comment by jaakristioja** [comment]
@gholmlund I agree. I just committed 8e449eaa95a16b162363bcd925efc70eeed5093b to provide such a file. Could you please verify whether this solves the problem?

**Comment by gholmlund** [comment]
Building the master does show we have a bibletime_ui_en_US.qm file now. This should fix the problem.
