### ISSUE TITLE
[ENHANCEMENT] macOS brew formula and notarization

### ISSUE THREAD

**Issue by niklasarnitz** [bibletime/bibletime#442]
I'm currently in the process of creating a homebrew cask formula for bibletime.

During that process, I noticed that the bibletime executable isn't notarized, which means that it can only be used on arm macs when doing the old right-click -> open -> open even when there isn't a valid developer maneuver.

Is there a possibility to notarize the app?

**Comment by greg-hellings** [comment]
You are welcome to submit a PR that would add that feature. But I doubt anyone on the current development team has the wherewithal to tackle any macOS specific behavior.

**Comment by jaakristioja** [comment]
That is indeed the situation. I'm certainly not going to do that at this time. I don't have the necessary hardware/software to test any of this, and the terms of service of their "notarization" process and Apple ID, and the license agreements for their hardware/software would also most likely not be acceptable to me.

**Comment by gholmlund** [comment]
I have been packaging BibleTime for the Mac. I believe notarization would require the packager to be an "apple developer". There is a fee for this which I believe is $100/year. I don't plan to do this. I someone is willing or already has done this, I could help them with packaging BibleTime.

**Comment by jaakristioja** [comment]
I'm also a bit skeptical about having someone from outside our development team doing an "official" package of BibleTime for Mac, because this might turn out to be problematic. But I'm not against unofficial packages, so feel free to create such packages yourself.

But I think it is safe to say that it is currently not possible for the BibleTime team to provide notarized packages for Mac, unfortunately.

Closing.
