### ISSUE TITLE
[BUG] 461 seems to have been deleted this seems very un-Christian

Please restore issue 461

### ISSUE THREAD

**Issue by slackguru** [bibletime/bibletime#462]
**Bug description**
A clear and concise description of what the bug is. Please only describe one issue per bug report.

**Steps to reproduce**

**Expected behavior**

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**System information:**
 - OS and OS version: [e.g. Debian 10, Windows 10]
 - BibleTime Version [e.g. 3.1_rc2]
 - How BibleTime was installed [e.g. from system packages, Snap, Flatpak, installer, compiled from source code]
 - Versions of modules related to the crash (if known)
 - (If compiled from source) Sword Version
 - (If compiled from source) Qt Version

**Additional context**
Add any other context about the problem here, e.g. including output of `bibletime --debug` and/or backtraces in case of crashes.

**Comment by jaakristioja** [comment]
#461 is not deleted, it is closed, but discussion is not locked, so afaik you can continue to comment under that issue. No?

**Comment by jaakristioja** [comment]
Ah, I see you already managed to continue discussion there, so no need to keep this one open.

Closing this as invalid, especially as the first comment is invalid (only contains the template) and all info is contained in the title.

Also, as the title of this issue is of rather accusatory nature, I'm offering You the option to kindly ask us to delete this issue from GitHub should You judge such accusations to be a bad public example of good behavior.
