### ISSUE TITLE
Strong's in MAG windows does not work for new user

### ISSUE THREAD

**Issue by gholmlund** [bibletime/bibletime#77]
For a new install of BibleTime, even if the correct lexicons and Bibles are installed and used, Strong's info will not appear in the MAG window. By new install I am referring to not having saved a bibletimerc file and therefore does not have a default Hebrew|Greek Strong's Lexicon configured.

The problem is in BtInfoRendering::decodeStrongs. If the btConfig entry for the Strong's Lexicon has not been choosen, no module is found and the information is not displayed.

It can be argued that the person should go configure the Strong's lexicons. The problem is that most people do not know to do this.

Possible solutions:
If no default module is set, find the first Lexicon with the correct feature (GreekDef, HebrewDef) and use it. This is complicated by the fact that not all Greek|Hebrew Lexicons will work. See Bug #52.

Show the user a dialog that explains the need to configure the Strong's Lexicons. The next issue is when to do this. Doing it just because the cursor hovers oven a Bible with strong's does not seem right. Doing it at startup if programmatic because you need to install Bibles and Lexicons first. Perhaps doing it when the first Bible window is opened?

**Comment by sandysson** [comment]
What has happened to the MAG function (and therefore the support for Strongs)?

The mag window does not come up properly as it used to in the side bar (Bibletime version 2.10.1 running under OpenSUSE leap 42.2 / Gnome 3.20.2). The window can be switched on and off, but its properties are rather 'ghostly' (for want of a better word!). It can be moved around the desktop, but it contains the content of the background at the place where it was last closed (i.e. is almost invisible) remains totally dysfunctional.

**Comment by gholmlund** [comment]
I installed OpenSUSE leap 42.2 with Gnome and installed BibleTime 2.10.1 from the OpenSUSE repositories. It works perfectly for me.

**Comment by sandysson** [comment]
Well, there was certainly something seriously wrong with the Mag view
in my installation. My BibleTime version is 2.10.1-4.38 (64-bit) to be
more precise.
Actually, it had been displaying this behaviour since Leap 42.1. 

For some reason, the situation has now improved inasmuch as the mag
window has stopped its ghostly behaviour and shows the Strongs
references correctly, but not as previously (i.e. under OpenSuse 13.1),
the meanings of the words. The meanings can apparently now only be
obtained by opening an extra MLStrong window and searching in that for
the  given Strongs reference number. Or am I mistaken?





On Sun, 2016-11-20 at 15:08 -0800, gholmlund wrote:
> > I installed OpenSUSE leap 42.2 with Gnome and installed BibleTime
2.10.1 from the OpenSUSE repositories. It works perfectly for me.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/bibletime
/bibletime","title":"bibletime/bibletime","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/bibletime/bibletime"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@gholmlund in #77: I installed
OpenSUSE leap 42.2 with Gnome and installed BibleTime 2.10.1 from the
OpenSUSE repositories. It works perfectly for
me."}],"action":{"name":"View
Issue","url":"https://github.com/bibletime/bibletime/issues/77#issuec
omment-261813525"}}}

**Comment by gholmlund** [comment]
You should read the description of this issue. Basically the MAG window only shows the Strong's numbers, UNLESS the Hebrew and Greek Strong's lexicons are configured in the Settings dialog.

**Comment by sandysson** [comment]
Thanks for your help. I forced a reinstallation of BibleTime and the
MAG window now shows the Strongs numbers. And, of course, with the
right choice of standard works, the meanings are display as well!
Many thanks.

On Sun, 2016-11-20 at 21:05 -0800, gholmlund wrote:
> > > You should read the description of this issue. Basically the MAG
window only shows the Strong's numbers, UNLESS the Hebrew and Greek
Strong's lexicons are configured in the Settings dialog.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/bibletime
/bibletime","title":"bibletime/bibletime","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/bibletime/bibletime"}},"updates":{"
snippets":[{"icon":"PERSON","message":"@gholmlund in #77: You should
read the description of this issue. Basically the MAG window only
shows the Strong's numbers, UNLESS the Hebrew and Greek Strong's
lexicons are configured in the Settings
dialog."}],"action":{"name":"View
Issue","url":"https://github.com/bibletime/bibletime/issues/77#issuec
omment-261844371"}}}

**Comment by gholmlund** [comment]
Fix bug #77 - MAG Strongs does not work unless config settings have been saved. Added function to get the first available Strongs module if the config settings have not set to a standard Strongs module.
